Análisis de Caso
Nombre del tema: Aplicación de NumPy en el Análisis de Datos

1. Carga y estructuración de datos:
○ Crea un array NumPy con datos financieros simulados (por ejemplo,precios de acciones en diferentes días).
○ Organiza los datos en una matriz de 5x5, donde cada fila representa una acción y cada columna un día de cotización.

In [ ]:
#importamos la librería numpy
import numpy as np

#creamos un array con datos financieros con 25 ejemplos
datos_financieros = np.array([[1000, 1500, 2000, 1500, 1390],   
                              [800, 1200, 1800, 1600, 1000],    
                              [200, 300, 400, 350, 480],      
                              [50, 75, 100, 50, 100],        
                              [150, 225, 300,200, 230 ]])     


#organizamos los datos en una matriz de 5 filas y 5 columnas
datos_financieros = datos_financieros.reshape(5, 5) 
#mostramos la matriz
print("Matriz de datos financieros:")
print(datos_financieros)

Matriz de datos financieros:
[[1000 1500 2000 1500 1390]
 [ 800 1200 1800 1600 1000]
 [ 200  300  400  350  480]
 [  50   75  100   50  100]
 [ 150  225  300  200  230]]


2. Análisis y transformación de datos:
○ Obtén el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.
○ Calcula la variación porcentual diaria de cada acción.
○ Aplica funciones matemáticas como logaritmo, exponencial o normalización sobre los datos.

In [2]:
#obtenemos el promedio de cada fila y mostramos el resultado    
promedios_filas = np.mean(datos_financieros, axis=1)    
print("\nPromedio de cada fila:")
print(promedios_filas)


Promedio de cada fila:
[1478. 1280.  346.   75.  221.]


In [3]:
#calculamos el valor máximo de cada fila y mostramos el resultado
maximos_filas = np.max(datos_financieros, axis=1)
print("\nValor máximo de cada fila:")
print(maximos_filas)


Valor máximo de cada fila:
[2000 1800  480  100  300]


In [4]:
#calculamos el minimo de cada fila y mostramos el resultado
minimos_filas = np.min(datos_financieros, axis=1)
print("\nValor mínimo de cada fila:")
print(minimos_filas)


Valor mínimo de cada fila:
[1000  800  200   50  150]


In [5]:
#Calculamos la variación porcentual de cada fila y mostramos el resultado
variacion_porcentual = np.diff(datos_financieros, axis=1) / datos_financieros[:, :-1] * 100 
print("\nVariación porcentual de cada fila:")
print(variacion_porcentual)


Variación porcentual de cada fila:
[[ 50.          33.33333333 -25.          -7.33333333]
 [ 50.          50.         -11.11111111 -37.5       ]
 [ 50.          33.33333333 -12.5         37.14285714]
 [ 50.          33.33333333 -50.         100.        ]
 [ 50.          33.33333333 -33.33333333  15.        ]]


In [6]:
#calculamnos el logaritmo natural de cada elemento de la matriz y mostramos el resultado
logaritmos_naturales = np.log(datos_financieros)    
print("\nLogaritmo natural de cada elemento de la matriz:")
print(logaritmos_naturales)


Logaritmo natural de cada elemento de la matriz:
[[6.90775528 7.31322039 7.60090246 7.31322039 7.23705903]
 [6.68461173 7.09007684 7.49554194 7.37775891 6.90775528]
 [5.29831737 5.70378247 5.99146455 5.85793315 6.1737861 ]
 [3.91202301 4.31748811 4.60517019 3.91202301 4.60517019]
 [5.01063529 5.4161004  5.70378247 5.29831737 5.43807931]]


In [7]:
#calculamos la exponencial de cada elemento de la matriz y mostramos el resultado
exponenciales = np.exp(datos_financieros)
print("\nExponencial de cada elemento de la matriz:")
print(exponenciales)


Exponencial de cada elemento de la matriz:
[[            inf             inf             inf             inf
              inf]
 [            inf             inf             inf             inf
              inf]
 [7.22597377e+086 1.94242640e+130 5.22146969e+173 1.00709089e+152
  2.89301918e+208]
 [5.18470553e+021 3.73324200e+032 2.68811714e+043 5.18470553e+021
  2.68811714e+043]
 [1.39370958e+065 5.20305514e+097 1.94242640e+130 7.22597377e+086
  7.72201850e+099]]


C:\Users\JuanCaifal\AppData\Local\Temp\ipykernel_58696\3483997953.py:2: RuntimeWarning: overflow encountered in exp
  exponenciales = np.exp(datos_financieros)


In [8]:
#claculamos la normalización de cada fila y mostramos el resultado
normalizacion_filas = (datos_financieros - np.min(datos_financieros, axis=1, keepdims=True)) / (np.max(datos_financieros, axis=1, keepdims=True) - np.min(datos_financieros, axis=1, keepdims=True))    
print("\nNormalización de cada fila:")
print(normalizacion_filas)


Normalización de cada fila:
[[0.         0.5        1.         0.5        0.39      ]
 [0.         0.4        1.         0.8        0.2       ]
 [0.         0.35714286 0.71428571 0.53571429 1.        ]
 [0.         0.5        1.         0.         1.        ]
 [0.         0.5        1.         0.33333333 0.53333333]]


3. Optimización y selección de datos:
○ Utiliza indexación avanzada para extraer información específica, como el rendimiento de una acción en un día determinado.
○ Aplica broadcasting para realizar operaciones sin necesidad de bucles.

In [9]:
#utilizamos la indexacion sobre la matriz para obtener el valor de la fila 2 y columna 3
valor_fila_2_columna_3 = datos_financieros[1, 2]    
print("\nValor de la fila 2 y columna 3:")
print(valor_fila_2_columna_3)


Valor de la fila 2 y columna 3:
1800


In [12]:
#aplicamos broadcasting para sumar un vector a cada fila de la matriz datos_financieros   

vector_suma = np.array([10, 20, 30, 40, 50])    


datos_ajustados = datos_financieros + vector_suma

# mostamos matriz original
print(datos_financieros)   

#mostramos la nueva matriz
print(datos_ajustados)


[[1000 1500 2000 1500 1390]
 [ 800 1200 1800 1600 1000]
 [ 200  300  400  350  480]
 [  50   75  100   50  100]
 [ 150  225  300  200  230]]
[[1010 1520 2030 1540 1440]
 [ 810 1220 1830 1640 1050]
 [ 210  320  430  390  530]
 [  60   95  130   90  150]
 [ 160  245  330  240  280]]


4. Comparación con otros métodos:
○ Analiza cómo se podrían realizar estas tareas sin NumPy y compara la eficiencia en términos de código y rendimiento computacional.

In [13]:
import sys 


py_list = list( range ( 1000 )) 
np_array = np.arange( 1000 )   
print ( "Tamaño de la lista de Python: " , sys.getsizeof(py_list)) 
print ( "Tamaño de la matriz Numpy: " , sys.getsizeof(np_array))

Tamaño de la lista de Python:  8056
Tamaño de la matriz Numpy:  4112


In [15]:
import time   

# Define dos listas de Python
py_list1 = list ( range ( 1000000 )) 
py_list2 = list ( range ( 1000000 , 2000000 ))   

# Define dos matrices Numpy
np_array1 = np.arange( 1000000 ) 
np_array2 = np.arange( 1000000 , 2000000 )   

# Añadiendo listas de Python
start_time = time.time() 
result_list = [a + b for a, b in  zip (py_list1, py_list2)] 
print ( "Tiempo necesario para añadir listas de Python: " , time.time() - start_time)   

# Añadiendo matrices Numpy
start_time = time.time() 
result_array = np_array1 + np_array2 
print ( "Tiempo necesario para añadir matrices Numpy: " , time.time() -start_time)

Tiempo necesario para añadir listas de Python:  0.09177923202514648
Tiempo necesario para añadir matrices Numpy:  0.0020110607147216797


Con estos dos ejemplos mostramos la eficiencia de numpy sobre python normal.