In [3]:
#importamos la librería numpy
import numpy as np

#Creamos una matriz de 3x3 con  numeros enteros del 1 al 9
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



#suma 10 a cada elemento de la matriz
matriz += 10

#imprimimos la matriz
print("------------------------------------")
print(matriz)


#Multiplicamos la matriz por 2
matriz *= 2

#imprimimos la matriz
print("------------------------------------")
print(matriz)

#extraemos los elementos mayores a 5 utilizando una selección condicional
mayores_a_5 = matriz[matriz > 5]

#imprimimos los elementos mayores a 5
print("------------------------------------")
print(mayores_a_5)

#asigmanos a la matriz a una nueva variable B = A y modifica un valor de B  
B = matriz.copy()
B[0, 0] = 100

#imprimimos la matriz original y la modificada
print("------------------------------------")
print("Matriz original:")
print(matriz)
print("------------------------------------")
print("Matriz modificada:")
print(B)




------------------------------------
[[11 12 13]
 [14 15 16]
 [17 18 19]]
------------------------------------
[[22 24 26]
 [28 30 32]
 [34 36 38]]
------------------------------------
[22 24 26 28 30 32 34 36 38]
------------------------------------
Matriz original:
[[22 24 26]
 [28 30 32]
 [34 36 38]]
------------------------------------
Matriz modificada:
[[100  24  26]
 [ 28  30  32]
 [ 34  36  38]]
