In [1]:
#importamos la librería numpy
import numpy as np

#Creamos un arreglo x con np.arange(1, 17) y redimensionalo en una matriz de 4x4
x = np.arange(1, 17).reshape(4, 4)

#Imprimimos el arreglo x
print("--------------------------------------")
print("Arreglo x:")
print(x)

#Generamos un arreglo de 10 elementos equidistantes entre 0 y 100 usando np.linspace
y = np.linspace(0, 100, 10)

#Imprimimos el arreglo y
print("--------------------------------------")
print("Arreglo y:")
print(y)

#Crea una matriz aleatoria de 3x3 con enteros entre 1 y 20 usando np.random.randint
z = np.random.randint(1, 21, size=(3, 3))
#Imprimimos la matriz z
print("--------------------------------------")
print("Matriz z:")
print(z)

#aplica np.sqrt() y np.log() sobre las matrices creadas(cuando sea posible)
print("--------------------------------------")
print("Aplicando np.sqrt() y np.log() a las matrices creadas:")
print("Matriz x (sqrt):")
print(np.sqrt(x))
print("Matriz x (log):")    
print(np.log(x))


#que diferencia hay en la forma de aplicar funciones sobre arreglos enteros vs flotantes?
print("--------------------------------------")
print("Diferencia entre aplicar funciones a arreglos enteros vs flotantes:")            
print("Las funciones como np.sqrt() y np.log() pueden generar resultados no enteros,")
print("por lo que al aplicarlas a arreglos enteros, los resultados se convierten en flotantes.")
print("Por ejemplo, np.sqrt(4) es 2.0, no 2.")






--------------------------------------
Arreglo x:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------
Arreglo y:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
--------------------------------------
Matriz z:
[[18  8 17]
 [ 6 19  3]
 [15  6 18]]
--------------------------------------
Aplicando np.sqrt() y np.log() a las matrices creadas:
Matriz x (sqrt):
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]
Matriz x (log):
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]
--------------------------------------
Diferencia entre aplicar funciones a arreglos enteros vs flotantes:
Las func